
-- Create a table to track search queries
create table if not exists search_logs (
  id bigint generated by default as identity primary key,
  query text not null,
  version text,
  testament text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on RLS
alter table search_logs enable row level security;

-- Allow anonymous users to insert logs (anyone can search)
create policy "Enable insert for all users" on search_logs for insert with check (true);

-- Allow developers (authenticated or specific role) to view logs
-- For simplicity, we might allow public reading for now or just service role
-- But typically we only want admins to read.
-- For this app, let's allow "service_role" or if you browse the table in dashboard you are fine.
-- We won't add a select policy for anon users to protect user privacy.
